"""
PDF Report Generator for Audit Pro Enterprise

Generates professional PDF reports for:
- Audit Reports
- NC/OFI Summary Reports
- CAR Status Reports
- Management Review Reports
"""

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak, Image
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from datetime import datetime
import os


class PDFGenerator:
    """Base PDF generator class."""

    def __init__(self, filename, title="Audit Report"):
        """Initialize PDF generator."""
        self.filename = filename
        self.title = title
        self.doc = SimpleDocTemplate(
            filename,
            pagesize=letter,
            rightMargin=72,
            leftMargin=72,
            topMargin=72,
            bottomMargin=18
        )
        self.styles = getSampleStyleSheet()
        self.story = []

        # Custom styles
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#1f77b4'),
            spaceAfter=30,
            alignment=TA_CENTER
        ))

        self.styles.add(ParagraphStyle(
            name='CustomHeading',
            parent=self.styles['Heading2'],
            fontSize=16,
            textColor=colors.HexColor('#667eea'),
            spaceAfter=12,
            spaceBefore=12
        ))

    def add_header(self, title, subtitle=None):
        """Add report header."""
        self.story.append(Paragraph(title, self.styles['CustomTitle']))

        if subtitle:
            self.story.append(Paragraph(subtitle, self.styles['Normal']))

        self.story.append(Spacer(1, 0.2 * inch))

        # Add horizontal line
        line_data = [['_' * 100]]
        line_table = Table(line_data, colWidths=[6.5 * inch])
        line_table.setStyle(TableStyle([
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.grey),
            ('FONTSIZE', (0, 0), (-1, -1), 8)
        ]))
        self.story.append(line_table)
        self.story.append(Spacer(1, 0.3 * inch))

    def add_metadata(self, metadata):
        """Add report metadata (date, generated by, etc.)."""
        data = []
        for key, value in metadata.items():
            data.append([f"<b>{key}:</b>", str(value)])

        table = Table(data, colWidths=[2 * inch, 4.5 * inch])
        table.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
            ('ALIGN', (0, 0), (0, -1), 'RIGHT'),
            ('ALIGN', (1, 0), (1, -1), 'LEFT'),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6)
        ]))

        self.story.append(table)
        self.story.append(Spacer(1, 0.3 * inch))

    def add_section(self, title, content):
        """Add a section with title and content."""
        self.story.append(Paragraph(title, self.styles['CustomHeading']))
        self.story.append(Paragraph(content, self.styles['Normal']))
        self.story.append(Spacer(1, 0.2 * inch))

    def add_table(self, data, col_widths=None, title=None):
        """Add a formatted table."""
        if title:
            self.story.append(Paragraph(title, self.styles['CustomHeading']))

        if col_widths is None:
            col_widths = [6.5 * inch / len(data[0])] * len(data[0])

        table = Table(data, colWidths=col_widths)

        # Style the table
        table.setStyle(TableStyle([
            # Header row
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#667eea')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 11),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            # Data rows
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('TEXTCOLOR', (0, 1), (-1, -1), colors.black),
            ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 1), (-1, -1), 9),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('GRID', (0, 0), (-1, -1), 1, colors.grey),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.lightgrey])
        ]))

        self.story.append(table)
        self.story.append(Spacer(1, 0.2 * inch))

    def build(self):
        """Build the PDF document."""
        self.doc.build(self.story)


def generate_audit_pdf(audit, nc_ofis=None, output_path=None):
    """
    Generate comprehensive audit report PDF.

    Args:
        audit: Audit model instance
        nc_ofis: List of NC/OFI findings for this audit
        output_path: Optional custom output path
    """
    if output_path is None:
        output_path = f"data/sample_pdfs/audit_report_{audit.audit_number}.pdf"

    # Ensure directory exists
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    # Create PDF generator
    pdf = PDFGenerator(output_path, f"Audit Report - {audit.audit_number}")

    # Header
    pdf.add_header(
        f"Audit Report: {audit.audit_number}",
        f"{audit.standard} - {audit.entity_name}"
    )

    # Metadata
    metadata = {
        "Audit Type": audit.audit_type,
        "Standard": audit.standard,
        "Entity": audit.entity_name,
        "Location": audit.entity_location or "N/A",
        "Department": audit.department or "N/A",
        "Lead Auditor": audit.lead_auditor,
        "Audit Date": audit.actual_date.strftime('%Y-%m-%d') if audit.actual_date else "Planned",
        "Duration": f"{audit.duration_hours:.1f} hours" if audit.duration_hours else "N/A",
        "Status": audit.status,
        "Overall Score": f"{audit.overall_score:.1f}/100" if audit.overall_score else "N/A",
        "Report Date": datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    }
    pdf.add_metadata(metadata)

    # Executive Summary
    if audit.executive_summary:
        pdf.add_section("Executive Summary", audit.executive_summary)

    # Audit Scope
    if audit.scope:
        pdf.add_section("Audit Scope", audit.scope)

    # Findings Summary
    findings_text = f"""
    This audit identified a total of {audit.total_findings} findings:
    <br/>
    - Major Non-Conformances: {audit.major_nc_count}
    <br/>
    - Minor Non-Conformances: {audit.minor_nc_count}
    <br/>
    - Observations for Improvement: {audit.ofi_count}
    <br/><br/>
    Overall compliance percentage: {audit.compliance_percentage:.1f}% if audit.compliance_percentage else "N/A"
    """
    pdf.add_section("Findings Summary", findings_text)

    # Detailed Findings Table
    if nc_ofis:
        findings_data = [['NC Number', 'Type', 'Category', 'Observation', 'Status']]

        for nc in nc_ofis:
            findings_data.append([
                nc.nc_number,
                nc.finding_type,
                nc.category or 'N/A',
                nc.observation[:50] + '...' if len(nc.observation) > 50 else nc.observation,
                nc.status
            ])

        pdf.add_table(
            findings_data,
            col_widths=[1.2*inch, 1*inch, 1*inch, 2.3*inch, 1*inch],
            title="Detailed Findings"
        )

    # Observations
    if audit.observations:
        pdf.add_section("Audit Observations", audit.observations)

    # Conclusions
    if audit.conclusions:
        pdf.add_section("Conclusions and Recommendations", audit.conclusions)

    # Build PDF
    pdf.build()

    return output_path


def generate_nc_summary_pdf(nc_ofis, date_from, date_to, output_path=None):
    """
    Generate NC/OFI summary report PDF.

    Args:
        nc_ofis: List of NC/OFI findings
        date_from: Start date for report period
        date_to: End date for report period
        output_path: Optional custom output path
    """
    if output_path is None:
        output_path = f"data/sample_pdfs/nc_summary_{datetime.now().strftime('%Y%m%d')}.pdf"

    # Ensure directory exists
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    # Create PDF generator
    pdf = PDFGenerator(output_path, "NC/OFI Summary Report")

    # Header
    pdf.add_header(
        "Non-Conformance & OFI Summary Report",
        f"Period: {date_from.strftime('%Y-%m-%d')} to {date_to.strftime('%Y-%m-%d')}"
    )

    # Summary Statistics
    total_nc = len([nc for nc in nc_ofis if nc.finding_type in ['Major NC', 'Minor NC']])
    total_ofi = len([nc for nc in nc_ofis if nc.finding_type == 'OFI'])
    major_nc = len([nc for nc in nc_ofis if nc.finding_type == 'Major NC'])
    minor_nc = len([nc for nc in nc_ofis if nc.finding_type == 'Minor NC'])
    open_nc = len([nc for nc in nc_ofis if nc.status in ['Open', 'In Progress']])
    closed_nc = len([nc for nc in nc_ofis if nc.status in ['Closed', 'Verified']])

    summary_data = [
        ['Metric', 'Count'],
        ['Total NC', str(total_nc)],
        ['Major NC', str(major_nc)],
        ['Minor NC', str(minor_nc)],
        ['OFI', str(total_ofi)],
        ['Open', str(open_nc)],
        ['Closed', str(closed_nc)],
        ['Closure Rate', f"{(closed_nc/len(nc_ofis)*100):.1f}%" if nc_ofis else "0%"]
    ]

    pdf.add_table(summary_data, col_widths=[3*inch, 3.5*inch], title="Summary Statistics")

    # Detailed NC/OFI Table
    nc_data = [['NC Number', 'Type', 'Category', 'Severity', 'Status', 'Due Date']]

    for nc in nc_ofis[:50]:  # Limit to 50 for PDF
        nc_data.append([
            nc.nc_number,
            nc.finding_type,
            nc.category or 'N/A',
            nc.severity or 'N/A',
            nc.status,
            nc.target_closure_date.strftime('%Y-%m-%d') if nc.target_closure_date else 'N/A'
        ])

    pdf.add_table(
        nc_data,
        col_widths=[1.1*inch, 0.8*inch, 1*inch, 0.8*inch, 1*inch, 1.3*inch],
        title="NC/OFI Details"
    )

    # Build PDF
    pdf.build()

    return output_path


def generate_car_status_pdf(cars, output_path=None):
    """
    Generate CAR status report PDF.

    Args:
        cars: List of CorrectiveAction instances
        output_path: Optional custom output path
    """
    if output_path is None:
        output_path = f"data/sample_pdfs/car_status_{datetime.now().strftime('%Y%m%d')}.pdf"

    # Ensure directory exists
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    # Create PDF generator
    pdf = PDFGenerator(output_path, "CAR Status Report")

    # Header
    pdf.add_header(
        "Corrective Action Request Status Report",
        f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    )

    # Summary Statistics
    total_cars = len(cars)
    completed = len([car for car in cars if car.status == 'Verified'])
    in_progress = len([car for car in cars if car.status in ['Submitted', 'Approved', 'In Progress']])
    draft = len([car for car in cars if car.status == 'Draft'])

    summary_data = [
        ['Status', 'Count', 'Percentage'],
        ['Total CARs', str(total_cars), '100%'],
        ['Completed (Verified)', str(completed), f"{(completed/total_cars*100):.1f}%" if total_cars else "0%"],
        ['In Progress', str(in_progress), f"{(in_progress/total_cars*100):.1f}%" if total_cars else "0%"],
        ['Draft', str(draft), f"{(draft/total_cars*100):.1f}%" if total_cars else "0%"]
    ]

    pdf.add_table(summary_data, col_widths=[2.5*inch, 2*inch, 2*inch], title="CAR Summary")

    # Detailed CAR Table
    car_data = [['CAR Number', 'Method', 'Status', '8D Progress', 'Due Date', 'Verified']]

    for car in cars:
        progress = car.get_8d_progress() if car.method == '8D' else 0
        car_data.append([
            car.car_number,
            car.method,
            car.status,
            f"{progress:.0f}%" if car.method == '8D' else 'N/A',
            car.due_date.strftime('%Y-%m-%d') if car.due_date else 'N/A',
            '✓' if car.effectiveness_verified else '✗'
        ])

    pdf.add_table(
        car_data,
        col_widths=[1.2*inch, 0.8*inch, 1.1*inch, 1*inch, 1.1*inch, 0.8*inch],
        title="CAR Details"
    )

    # Build PDF
    pdf.build()

    return output_path


def generate_management_review_pdf(audits, nc_ofis, cars, kpis, output_path=None):
    """
    Generate management review report PDF.

    Args:
        audits: List of Audit instances
        nc_ofis: List of NC/OFI instances
        cars: List of CorrectiveAction instances
        kpis: Dictionary of KPIs
        output_path: Optional custom output path
    """
    if output_path is None:
        output_path = f"data/sample_pdfs/management_review_{datetime.now().strftime('%Y%m%d')}.pdf"

    # Ensure directory exists
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    # Create PDF generator
    pdf = PDFGenerator(output_path, "Management Review Report")

    # Header
    pdf.add_header(
        "Management Review Report",
        f"Period: {datetime.now().strftime('%Y-%m-%d')}"
    )

    # KPI Summary
    kpi_data = [
        ['Key Performance Indicator', 'Value', 'Target', 'Status'],
        ['Total Audits', str(kpis.get('total_audits', 0)), 'N/A', '✓'],
        ['Completion Rate', f"{kpis.get('completion_rate', 0):.1f}%", '≥80%', '✓' if kpis.get('completion_rate', 0) >= 80 else '✗'],
        ['Average Audit Score', f"{kpis.get('avg_score', 0):.1f}", '≥80', '✓' if kpis.get('avg_score', 0) >= 80 else '✗'],
        ['Open NC/OFI', str(kpis.get('open_nc', 0)), '≤10', '✓' if kpis.get('open_nc', 0) <= 10 else '✗'],
        ['NC Closure Rate', f"{kpis.get('nc_closure_rate', 0):.1f}%", '≥80%', '✓' if kpis.get('nc_closure_rate', 0) >= 80 else '✗']
    ]

    pdf.add_table(kpi_data, col_widths=[3*inch, 1.5*inch, 1*inch, 1*inch], title="Key Performance Indicators")

    # Build PDF
    pdf.build()

    return output_path
